
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const SIGNOUT_USER = 'SIGNOUT_USER';

// Might be subdivded in RETRIEVE_NEWS_ARTICLE, RETRIEVE_ORG_ARTICLE
export const RETRIEVE_ARTICLES = 'RETRIEVE_ARTICLES';
export const RETRIEVE_HOSPITAL_DATA = 'RETRIEVE_HOSPITAL_DATA';

